pipeline {
    agent any

    environment {
        /* Jenkins credentials */
        AWS_ECR_CREDENTIAL_ID = 'ecr-user'
        AWS_S3_CREDENTIAL_ID = 's3-credential'
        VM_ENTER_CREDENTIAL_ID = 'enter-vm-credential' // elice VM에 접속하기 위한 credential
        OSONDOSON_VM_CREDENTIAL_ID = 'team2-vm-credential' // VM 자체에 대한 credential (사용자 이름, 패스워드)

        /* AWS Info */
        ACCOUNT_ID = '014276069644'
        AWS_REGION = 'ap-northeast-2'
        ECR_REPO = '014276069644.dkr.ecr.ap-northeast-2.amazonaws.com/eeum-backend'

        /* S3 Info */
        BUCKET_NAME = 'eeum-config-bucket'

        /* VM Info */
        TARGET_HOST = '34.64.144.19'

        /* Container Info */
        CONTAINER_NAME = 'osondoson-backend'
        CONTAINER_PORT = 3500
    }

    stages {
        stage('Checkout') {
            steps {
                deleteDir() // 이전에 가져온 소스 코드를 모두 삭제
                checkout scm
                sh 'git checkout develop'
            }
        }

        stage('Append .env files') {
            steps {
                withAWS(region: "${AWS_REGION}", credentials: "${AWS_S3_CREDENTIAL_ID}") {
                    // S3로부터 .env 파일 다운로드
                    s3Download(file: "${env.WORKSPACE}/.env", bucket: "${BUCKET_NAME}", path: 'backend/.env', force: true)
                }
            }
        }

        stage('Docker build') {
            steps {
                sh "docker build -t ${ECR_REPO}:latest ."
            }
        }

        stage('Push to ECR') {
            steps {
                script {
                    // docker push
                    docker.withRegistry("https://${ECR_REPO}", "ecr:${AWS_REGION}:${AWS_ECR_CREDENTIAL_ID}") {
                        docker.image("${ECR_REPO}:latest").push()
                    }
                }
            }
        }
    }
}
